film1 = Film.create( { name: "The Shawshank Redemption", description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency." , rating: "", link: ""    } )
film2 = Film.create( { name: "The Godfather", description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son." , rating: "", link: ""    } )
film3 = Film.create( { name: "TThe Dark Knight", description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice." , rating: "", link: ""    } )
film4 = Film.create( { name: "Schindlers List", description: "In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis." , rating: "", link: ""    } )
film5 = Film.create( { name: "12 Angry Men", description: "
A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence." , rating: "", link: ""    } )
film6 = Film.create( { name: "Pulp Fiction", description: "The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption." , rating: "", link: ""    } )
film7 = Film.create( { name: "The Good, The Bad & The Ugly", description: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery." , rating: "", link: ""    } )
film8 = Film.create( { name: "Fight Club", description: "An insomniac office worker, looking for a way to change his life, crosses paths with a devil-may-care soap maker, forming an underground fight club that evolves into something much, much more..." , rating: "", link: ""    } )
film9 = Film.create( { name: "Goodfellas", description: "Henry Hill and his friends work their way up through the mob hierarchy." , rating: "", link: ""    } )
film10 = Film.create( { name: "City of God", description: "Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths: one becomes a photographer, the other a drug dealer." , rating: "", link: ""    } )


Post.create( { name: "Laurence", title: "The Shawshank Redemption review", content: "Very good touching movie ", film_id: film1.id})
Post.create( { name: "Laurence", title: "The Godfather review", content: "Was at the front of my seat ", film_id: film2.id})
Post.create( { name: "Laurence", title: "The Dark Knight review", content: " Heath ledger was amazing ", film_id: film3.id})
Post.create( { name: "Laurence", title: "Schindlers List review", content: "Haven't seen it yet", film_id: film4.id})
Post.create( { name: "Laurence", title: "12 Angry men review", content: "Haven't seen it yet ", film_id: film5.id})
Post.create( { name: "Laurence", title: "Pulp Fiction review", content: "Haven't seen it yet", film_id: film6.id})
Post.create( { name: "Laurence", title: "The Good, The Bad & The Ugly", content: "Haven't seen it yet", film_id: film7.id})
Post.create( { name: "Laurence", title: "Fight Club", content: "Haven't seen it yet", film_id: film8.id})
Post.create( { name: "Laurence", title: "Goodfellas", content: "Haven't seen it yet", film_id: film9.id})
Post.create( { name: "Laurence", title: "City of God", content: "Haven't seen it yet", film_id: film10.id})
